[package]
name = "ite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = {version="5.101.0",features = ["wide"]}
lsp-types = "0.94.1"
pad = "0.1.6"
serde_json = "1.0.108"
serde = "1.0.192"